site_name: Puhuri Documentation
extra:
  analytics:
    provider: google
    property: G-9MPBK2ZXGH
extra_css:
  - assets/css/styles.css
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.tabbed:
        alternate_style: true


nav:
  - "index.md"
  - About:
      - "architecture.md"
      - "branding.md"
      - "terminology.md"
      - "environments.md"
      - Documents:
          - "documents/statistics_pp.md"
          - "documents/statistics_tos.md"
  - Resource Allocators:
      - "resource-allocators-overview.md"
      - Custom Portal Integration:
          - "resource-allocators.md"
          - API Guide:
              - "API guide/common.md"
              - "API guide/authentication.md"
              - "API guide/project.md"
              - "API guide/project-permissions.md"
              - "API guide/resource-allocation-management.md"
              - "API guide/listing-users-resources.md"
          - "integration-with-puhuri-aai.md"
      - "dedicated-puhuri-portal.md"
      - "shared-puhuri-portal.md"
  - Service Providers:
      - "service-providers.md"
      - SDK Guide:
          - "SDK guide/initial-setup.md"
          - "SDK guide/allocation-management-sp.md"
  - IdP Integration:
      - "idp_integration/index.md"
      - eduGAIN integration: idp_integration/requirements-edugain.md
      - Direct integration: idp_integration/requirements-direct.md
      - Attributes: idp_integration/attributes.md
      - Use cases:
          - National Portal and LUMI: idp_integration/use-cases/national-portal-integration.md
  - User Guides:
      - "user_guides/myaccessid_registration.md"
      - "user_guides/myaccessid_account_linking.md"
      - "user_guides/myaccessid-ssh-key.md"
      - Dedicated Puhuri Portal:
          - "user_guides/user_guide_dedicated/organization_and_project_management.md"
          - "user_guides/user_guide_dedicated/inviting_members.md"
          - "user_guides/user_guide_dedicated/project_modification.md"
          - "user_guides/user_guide_dedicated/project_approval.md"
      - Shared Puhuri Portal:
          - "user_guides/user_guide_shared/organization_and_project_management_shared.md"
          - "user_guides/user_guide_shared/membership_management_shared.md"
          - "user_guides/user_guide_shared/project_modification_shared.md"
          - "user_guides/user_guide_shared/project_approval_shared.md"
      - "user_guides/usage_reports.md"
      - "user_guides/user_roles.md"
